import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import CannonicalLink from "../components/CannonicalLink";
import generateSchemaMarkup from "../configuration/schemaMarkup";
import Script from "next/script";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const schemaData = JSON.stringify(generateSchemaMarkup());
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <head>
          <Script
            id="json-ld-schema"
            type="application/ld+json"
            strategy="afterInteractive"
          >
            {schemaData}
          </Script>
          <meta
            name="google-site-verification"
            content="68QqDtrfi3at6FPsShdh8LdW7gr73HV7A9QW6XGDGmk"
          />
          <meta name="robots" content="index, follow" />
          <CannonicalLink />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
